name: amplify_push_notifications_pinpoint
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  amplify_push_notifications_pinpoint_android: 0.6.4-rc.1
  amplify_push_notifications_pinpoint_ios: 0.6.4-rc.1
  amplify_core: 0.6.4-rc.1
  aws_common: ^0.1.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  aws_signature_v4: ^0.1.0
  smithy: ^0.1.0
  smithy_aws: ^0.1.0

dev_dependencies:
  amplify_lints: ^1.0.0
  amplify_test:
    path: ../../../amplify_test
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: amplify_push_notifications_pinpoint_android
      ios:
        default_package: amplify_push_notifications_pinpoint_ios
